### ISSUE TITLE
bug: invalid hyperlink in documentation

### ISSUE THREAD

**Issue by aivantsov** [agorapulse/pierrot#35]
The hyperlink in the documentation on [how to install Pierrot using the latest binaries](https://agorapulse.github.io/pierrot/#_installation) from the release page is invalid:

- expected https://github.com/agorapulse/pierrot/releases/latest
- but was: https://github.com/agorapulse/micronaut-worker/releases/latest

FYI: @jvdrean @musketyr

**Comment by musketyr** [comment]
thanks for the fix!
