### ISSUE TITLE
Simple search query doesn't appear to be working

### ISSUE THREAD

**Issue by syedwasimali** [agorapulse/pierrot#56]
Following the documentation and cannot get the query to work. 

Documentation: https://agorapulse.github.io/pierrot/#_full_syntax

> $ pierrot search 'org:xyz filename:dependabot.yml'
> Searching content for '"org:xyz filename:dependabot.yml"'!
> Found 0 results!

Rather than look for the `file`, it appears to search the content in the repos.

**Comment by syedwasimali** [comment]
I looked through the code and discovered that I need to drop the single quotes around the query string.

Thank you for building the tool and sharing it.

**Comment by musketyr** [comment]
Thank you @syedwasimali. Exactly, no need for the quotes unless you really want to search the exact match within the quotes.
